repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-json
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-yaml
    args: ['--unsafe']
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']
  - id: pretty-format-json
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: https://github.com/gitleaks/gitleaks
  rev: v8.16.1
  hooks:
  - id: gitleaks
    name: detect hardcoded secrets
    entry: gitleaks protect --verbose --redact --staged
    language: golang
    pass_filenames: false
